# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{apprise}
  s.version = "0.9.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Manfred Stienstra", "Eloy Duran"]
  s.date = %q{2009-11-01}
  s.default_executable = %q{apprise}
  s.description = %q{Apprise gives an overview of the dependencies of a Rails application.}
  s.email = ["manfred@fngtps.com", "eloy@fngtps.com"]
  s.executables = ["apprise"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "TODO",
     "VERSION",
     "apprise.gemspec",
     "bin/apprise",
     "design/requirements.txt",
     "lib/apprise.rb",
     "lib/apprise/bundler.rb",
     "lib/apprise/plugin.rb",
     "lib/apprise/plugin/base.rb",
     "lib/apprise/plugin/git.rb",
     "lib/apprise/plugin/svn.rb",
     "lib/tasks/apprise.rake",
     "rails/init.rb"
  ]
  s.homepage = %q{http://github.com/Fingertips/apprise}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Apprise gives an overview of the dependencies of a Rails application.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
